import type { Metadata } from "next";
import { Roboto_Condensed, Cormorant } from "next/font/google";
import Header from "@/components/header";
import Footer from "@/components/footer";
import "./globals.css";

import { ToastContainer } from "react-toastify";
import "react-toastify/dist/ReactToastify.css";

const robotoCondensed = Roboto_Condensed({
  subsets: ["latin"],
  weight: ["300", "400", "500", "600", "700"],
});

const cormorant = Cormorant({
  subsets: ["latin"],
  variable: "--font-cormorant",
  weight: ["300", "400", "500", "600", "700"],
});

export const metadata: Metadata = {
  title: "Manville Manor",
  // description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${robotoCondensed.className} ${cormorant.variable} bg-primary`}
      >
        <Header />
        {/* <main className="pt-28 md:pt-[8.875rem]">{children}</main> */}
        <main className="pt-[4.1875rem] md:pt-[5.3125rem]">{children}</main>

        <Footer />
        <ToastContainer />
      </body>
    </html>
  );
}
